Repository palantir/spark-tpcds-benchmark, pull requests merged in 2020-06, with the labels that each got.

#178 Add ability to generate data from the gensort program.
  changelog/@unreleased/pr-178.v2.yml
  spark-tpcds-benchmark-runner/build.gradle
  spark-tpcds-benchmark-runner/service/bin/gensort/gensort-linux-1.5.tar.gz
  spark-tpcds-benchmark-runner/service/bin/gensort/gensort_osx
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/TpcdsBenchmark.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/SortBenchmarkConfig.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/TpcdsBenchmarkConfig.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/GenSortDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/SortDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/TpcdsDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/util/DataGenUtils.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/GenSortDataGeneratorTest.java
  spark-tpcds-benchmark-runner/var/conf/config.yml
  versions.lock
  versions.props
Labels: merge when ready

#183 upload and transform gensort data to parquet
  changelog/@unreleased/pr-183.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/TpcdsBenchmarkRunner.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/DefaultParquetTransformer.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/GenSortDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/ParquetTransformer.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/TpcdsDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/paths/TpcdsPaths.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/util/DataGenUtils.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/AbstractLocalSparkTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/GenSortDataGeneratorTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/TpcdsDataGeneratorIntegrationTest.java
Labels: merge when ready

#185 improvement: use gensort data to perform sort benchmark
  changelog/@unreleased/pr-185.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/GenSortDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/queries/SortBenchmarkQuery.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/registration/TpcdsTableRegistration.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/GenSortTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/TpcdsDataGeneratorIntegrationTest.java
Labels: merge when ready

#186 rename Tpcds -> Benchmark and clean up paths
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/Benchmark.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/BenchmarkRunner.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/BenchmarkConfig.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/correctness/TpcdsQueryCorrectnessChecks.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/GenSortDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/TpcdsDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/metrics/BenchmarkMetric.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/metrics/BenchmarkMetrics.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/paths/BenchmarkPaths.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/registration/TableRegistration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/registration/TpcdsTableRegistration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/schemas/Schemas.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/AbstractLocalSparkTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/GenSortTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/TpcdsDataGeneratorIntegrationTest.java
Labels: merge when ready, no changelog

#187 improvement: support passing in a scale for gensort and wire to benchmark runner
  changelog/@unreleased/pr-187.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/Benchmark.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/BenchmarkRunner.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/BenchmarkConfig.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/SortBenchmarkConfig.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/GenSortDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/SortDataGenerator.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/GenSortTest.java
  spark-tpcds-benchmark-runner/var/conf/config.yml
Labels: merge when ready

#191 improvement: turn on AQE for better partitioning
  changelog/@unreleased/pr-191.v2.yml
  spark-tpcds-benchmark-runner/var/conf/config.yml
Labels: merge when ready

#189 add support for S3 + ABS filesystems
  .circleci/config.yml
  .circleci/template.sh
  build.gradle
  changelog/@unreleased/pr-189.v2.yml
  spark-tpcds-benchmark-runner/build.gradle
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/BenchmarkRunner.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/AzureBlobStoreConfiguration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/BenchmarkConfig.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/FilesystemConfiguration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/HadoopConfiguration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/S3Configuration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/config/SimpleFilesystemConfiguration.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/AbstractLocalSparkTest.java
  spark-tpcds-benchmark-runner/var/conf/config.yml
  versions.lock
  versions.props
Labels: merge when ready

#190 feature: generate gensort data in 1GB partitions
  changelog/@unreleased/pr-190.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/BenchmarkRunner.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/DefaultParquetTransformer.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/GenSortDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/ParquetTransformer.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/datagen/TpcdsDataGenerator.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/tpcds/paths/BenchmarkPaths.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/AbstractLocalSparkTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/GenSortTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/tpcds/datagen/TpcdsDataGeneratorIntegrationTest.java
Labels: merge when ready

#193 fix: rename clashing config fields
  changelog/@unreleased/pr-193.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/BenchmarkRunner.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/config/BenchmarkConfig.java
Labels: merge when ready

#194 fix: ignoreUnknownProperties in FileSystemConfiguration to get json subtypes to work
  changelog/@unreleased/pr-194.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/config/FilesystemConfiguration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/datagen/GenSortDataGenerator.java
Labels: merge when ready

#202 fix: use azure container name from config
  changelog/@unreleased/pr-202.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/Benchmark.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/config/AzureBlobStoreConfiguration.java
  spark-tpcds-benchmark-runner/var/conf/config.yml
Labels: autorelease, merge when ready

#221 improvement: add hadoop-cloud jars to get the right s3 committers
  .gitignore
  build.gradle
  changelog/@unreleased/pr-221.v2.yml
  jars/org/apache/spark/spark-hadoop-cloud_2.12/3.0.0/spark-hadoop-cloud_2.12-3.0.0.jar
  spark-tpcds-benchmark-runner/build.gradle
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/AbstractLocalSparkTest.java
  versions.lock
  versions.props
Labels: merge when ready

#224 fix: fix metrics schema
  changelog/@unreleased/pr-224.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/BenchmarkRunner.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/config/SparkConfiguration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/metrics/BenchmarkMetric.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/metrics/BenchmarkMetrics.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/BenchmarkMetricsTest.java
Labels: merge when ready

#231 resilience to more types of failure
  changelog/@unreleased/pr-231.v2.yml
  spark-tpcds-benchmark-runner/build.gradle
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/Benchmark.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/config/BenchmarksConfiguration.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/metrics/BenchmarkMetric.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/metrics/BenchmarkMetrics.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/paths/BenchmarkPaths.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/queries/QuerySessionIdentifier.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/BenchmarkMetricsTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/GenSortTest.java
  versions.lock
  versions.props
Labels: merge when ready

#236 fix: generate new QueryIdentifier for each iteration
  changelog/@unreleased/pr-236.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/Benchmark.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/metrics/BenchmarkMetrics.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/queries/QuerySessionIdentifier.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/BenchmarkMetricsTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/GenSortTest.java
Labels: merge when ready

#241 hive partition metrics to preclude conflicts
  changelog/@unreleased/pr-241.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/Benchmark.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/metrics/BenchmarkMetric.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/metrics/BenchmarkMetrics.java
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/queries/QuerySessionIdentifier.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/AbstractLocalSparkTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/TestIdentifiers.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/BenchmarkMetricsTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/GenSortTest.java
  spark-tpcds-benchmark-runner/src/test/java/com/palantir/spark/benchmark/datagen/TpcdsDataGeneratorIntegrationTest.java
Labels: autorelease, merge when ready

#242 increase YARN max executor failures in default config
  changelog/@unreleased/pr-242.v2.yml
  spark-tpcds-benchmark-runner/var/conf/config.yml
Labels: merge when ready

#243 fix: make iteration optional to fix backcompat of QuerySessionIdentifier
  changelog/@unreleased/pr-243.v2.yml
  spark-tpcds-benchmark-runner/src/main/java/com/palantir/spark/benchmark/queries/QuerySessionIdentifier.java
Labels: autorelease, merge when ready
